/*
This file contains a list of Reagenet Suppliers and the restriction enzymes they supply. The data comes from the REBASE database.

THIS FILE IS AUTO-GENERATED. DO NOT MODIFY THIS FILE MANUALLY.

To update the database, run the script in the script directory.
*/
package db

type SupplierRecord struct {
	Id      string
	Name    string
	Enzymes []string
}

var Suppliers = []SupplierRecord{
	{Id: "B", Name: "Thermo Fisher Scientific", Enzymes: []string{"EheI", "GsuI", "BfuI", "HpyF3I", "Alw21I", "PauI", "TatI", "HaeIII", "NsbI", "SmaI", "Alw44I", "XapI", "SfaAI", "SspDI", "VspI", "DraI", "NruI", "RruI", "BplI", "Hin6I", "BseJI", "BseMII", "KflI", "BglI", "Eco47I", "FspAI", "ClaI", "SgsI", "Hin1II", "KspAI", "SdaI", "BcuI", "RseI", "EcoRI", "PaeI", "PscI", "SgrDI", "EcoRII", "PdiI", "TscAI", "MspI", "PsyI", "BspLI", "Pfl23II", "SatI", "CseI", "XagI", "Bsp120I", "SpeI", "Bsu15I", "RsaI", "Eam1104I", "MunI", "MboII", "AjuI", "NcoI", "XmaJI", "Cfr13I", "XmiI", "BpiI", "BseLI", "Eco31I", "SgeI", "HincII", "FokI", "BmsI", "BglII", "MboI", "BstXI", "EcoT22I", "Bsh1236I", "HpaII", "BseGI", "MlsI", "SaqAI", "Tru1I", "TaiI", "Hin1I", "MssI", "DpnI", "BseSI", "Esp3I", "StuI", "MluI", "OliI", "SacI", "Csp6I", "Bsp143I", "MbiI", "Eco47III", "Eco72I", "AdeI", "NotI", "EcoRV", "XbaI", "Kpn2I", "Alw26I", "Eco91I", "LweI", "KpnI", "Hpy8I", "NheI", "Eco32I", "XhoI", "BsuRI", "NmuCI", "BshNI", "Psp5II", "BspPI", "Psp1406I", "LguI", "BoxI", "BauI", "BspOI", "AfaI", "FspBI", "SacII", "SalI", "MvaI", "SphI", "Eco24I", "PspFI", "Bsp1407I", "Acc65I", "CsiI", "HphI", "Bme1390I", "PagI", "BamHI", "Eco81I", "PfoI", "PsuI", "AanI", "BfmI", "Bpu1102I", "SsiI", "TasI", "CaiI", "BalI", "BspTI", "Eco57I", "MnlI", "Ppu21I", "EcoO109I", "MreI", "FaqI", "BseDI", "Bsh1285I", "Bst1107I", "Eco52I", "PstI", "PacI", "HpyF10VI", "Eco130I", "SduI", "TaaI", "HhaI", "Eam1105I", "AarI", "SfiI", "PteI", "MauBI", "XceI", "Ecl136II", "HapII", "BveI", "TaqI", "TauI", "AjiI", "BmeT110I", "Cfr10I", "AloI", "Cfr42I", "SchI", "Mva1269I", "AatII", "SmoI", "PvuI", "Bpu10I", "Eco88I", "BseXI", "Eco147I", "BseNI", "NdeI", "PasI", "Eco105I", "AasI", "Bsp119I", "BshTI", "Bsp68I", "PfeI", "SmiI", "Mph1103I", "ApaI", "ScaI", "BseMI", "AluI", "HinfI", "PdmI", "CpoI", "Van91I", "PvuII", "SspI", "HpaI", "Lsp1109I", "BcnI", "Cfr9I", "BclI", "BfoI", "AccI", "HindIII"}},
	{Id: "C", Name: "Minotech Biotechnology", Enzymes: []string{"SnaBI", "SmaI", "BseAI", "NruI", "SseBI", "BglI", "SgrBI", "EcoRI", "Sau3AI", "RsaI", "NcoI", "BglII", "MboI", "SstI", "BshFI", "ApaLI", "NaeI", "NotI", "EcoRV", "XbaI", "KpnI", "NheI", "BseBI", "PspPI", "SalI", "SphI", "BamHI", "CspAI", "SlaI", "BssAI", "StyI", "BsiSI", "PstI", "BseCI", "BstEII", "SfiI", "TaqI", "MspCI", "ScaI", "AluI", "HinfI", "PvuII", "SspI", "AsuII", "HpaI", "BclI", "HindIII"}},
	{Id: "E", Name: "Agilent Technologies", Enzymes: []string{"DpnI"}},
	{Id: "I", Name: "SibEnzyme Ltd.", Enzymes: []string{"AsuNHI", "BstSNI", "Rsr2I", "BstHHI", "FaeI", "ArsI", "BstV1I", "HaeIII", "BpmI", "AspA2I", "SmaI", "PsiI", "AhlI", "VspI", "DraI", "PspEI", "MalI", "VneI", "NruI", "PspOMI", "RigI", "BglI", "BstMWI", "BslFI", "BarI", "Sfr274I", "EcoRI", "KroNI", "PspXI", "MabI", "Bst6I", "Ama87I", "PspCI", "EcoICRI", "Sse9I", "BstSCI", "MspI", "MfeI", "AclI", "Bse8I", "DraIII", "BstENI", "MspA1I", "RsaI", "SbfI", "BsePI", "PkrI", "Bse1I", "Bse3DI", "MboII", "Bpu14I", "BstACI", "BstFNI", "Acc36I", "GluI", "PspN4I", "BstH2I", "FokI", "BstMAI", "AfeI", "BstBAI", "PstNI", "BseX3I", "BglII", "Bsp13I", "Acc16I", "SfaNI", "BstXI", "Zsp2I", "HpaII", "AsiGI", "AgsI", "Mly113I", "BstKTI", "BspACI", "BspFNI", "Tth111I", "BstAPI", "PciI", "TseFI", "AjnI", "AccBSI", "MluI", "HindII", "AoxI", "Psp124BI", "BstSLI", "HgaI", "FaiI", "BsuI", "PsrI", "EcoRV", "BstDSI", "XbaI", "Bsa29I", "DseDI", "AspLEI", "KpnI", "Bst4CI", "BisI", "FblI", "BsuRI", "ErhI", "ZrmI", "KroI", "BssNAI", "Bbv12I", "PctI", "SalI", "HspAI", "SphI", "MhlI", "AcuI", "BstNSI", "BmuI", "AcsI", "Acc65I", "BstX2I", "GlaI", "PalAI", "AsiSI", "BamHI", "PcsI", "AsuHPI", "BstSFI", "Mox20I", "MteI", "RsaNI", "AccB7I", "Ple19I", "PciSI", "AsuC2I", "MnlI", "Bme18I", "CciI", "AcoI", "DriI", "Fsp4HI", "PceI", "PstI", "Bse118I", "HpySE526I", "AluBI", "LmnI", "Tru9I", "Bsc4I", "Bso31I", "FatI", "SfiI", "BstF5I", "Bsp1720I", "FauI", "TaqI", "FalI", "BtrI", "ZraI", "BstMBI", "Bst2UI", "Bst2BI", "BstC8I", "GsaI", "XmaI", "AatII", "Bpu10I", "BmtI", "BstMCI", "AclWI", "AccB1I", "SetI", "BlsI", "AbsI", "CciNI", "BssECI", "BstDEI", "Bse21I", "BstAFI", "BstAUI", "BstPAI", "MspR9I", "Bsp19I", "SmiI", "PpsI", "ApaI", "Ksp22I", "BstV2I", "AluI", "Psp6I", "HinfI", "Kzo9I", "FriOI", "PvuII", "SspI", "SspMI", "FauNDI", "HpaI", "Sfr303I", "BssT1I", "AspS9I", "PspPPI", "SmiMI", "EgeI", "HindIII", "PspLI", "MroNI", "MroXI", "RgaI"}},
	{Id: "J", Name: "Nippon Gene Co., Ltd.", Enzymes: []string{"HaeIII", "NdeII", "SmaI", "Alw44I", "HaeII", "AvaI", "DraI", "NruI", "BglI", "EcoRI", "Sau3AI", "EcoRII", "MspI", "NsiI", "NciI", "SpeI", "RsaI", "MboII", "NcoI", "EcoT38I", "HincII", "FokI", "BglII", "BstXI", "Bsp1286I", "BsmI", "StuI", "MluI", "NspV", "SacI", "AcyI", "FspI", "AvaII", "NotI", "EcoRV", "XbaI", "KpnI", "NheI", "XhoI", "AseI", "AccIII", "SacII", "SalI", "SphI", "SwaI", "NarI", "BamHI", "StyI", "BalI", "EcoO109I", "AxyI", "PstI", "ScrFI", "HhaI", "BstEII", "SfiI", "TaqI", "AflII", "NdeI", "AccII", "ApaI", "ScaI", "AluI", "HinfI", "BssHII", "PvuII", "SspI", "HpaI", "BclI", "AccI", "AgeI", "HindIII", "Sau96I"}},
	{Id: "K", Name: "Takara Bio Inc.", Enzymes: []string{"PmaCI", "SnaBI", "EcoO65I", "BspT104I", "HaeIII", "SmaI", "HaeII", "DraI", "NruI", "MflI", "BglI", "ClaI", "EcoRI", "DdeI", "Sau3AI", "MspI", "PshAI", "SpeI", "MunI", "Sse8387I", "MboII", "NcoI", "HincII", "FokI", "BglII", "MboI", "BstXI", "EcoT22I", "Bsp1286I", "Hin1I", "ApaLI", "NaeI", "DpnI", "Tth111I", "BspT107I", "StuI", "MluI", "Aor51HI", "SacI", "FbaI", "NotI", "EcoRV", "XbaI", "KpnI", "NheI", "XhoI", "Psp1406I", "AfaI", "AccIII", "SacII", "SalI", "SphI", "BmgT120I", "Bsp1407I", "BstPI", "BamHI", "EcoT14I", "Eco81I", "Bpu1102I", "BalI", "BlnI", "EcoO109I", "BciT130I", "PshBI", "Bst1107I", "Eco52I", "PstI", "HhaI", "BanII", "SfiI", "HapII", "TaqI", "BmeT110I", "Cfr10I", "AatII", "PvuI", "AflII", "XspI", "NdeI", "EaeI", "AccII", "SmiI", "ApaI", "ScaI", "Aor13HI", "AluI", "VpaK11BI", "HinfI", "BssHII", "CpoI", "Van91I", "PvuII", "SspI", "HpaI", "BcnI", "AccI", "HindIII"}},
	{Id: "M", Name: "Roche Applied Science", Enzymes: []string{"SnaBI", "Asp718I", "HaeIII", "NdeII", "SmaI", "DraI", "Asp700I", "CfoI", "NruI", "SexAI", "ClaI", "EcoRI", "DdeI", "Sau3AI", "NsiI", "KspI", "DraIII", "SpeI", "RsaI", "MunI", "MaeI", "NcoI", "MaeII", "FokI", "BglII", "BstXI", "BbrPI", "DpnI", "BsmI", "StuI", "MluI", "HindII", "SacI", "Eco47III", "MaeIII", "NotI", "EcoRV", "XbaI", "KpnI", "NheI", "XhoI", "AflIII", "SfuI", "SalI", "MvaI", "SphI", "SwaI", "NarI", "BamHI", "MluNI", "BlnI", "PstI", "Tru9I", "SfiI", "TaqI", "AatII", "PvuI", "MroI", "NdeI", "ApaI", "ScaI", "AluI", "MvnI", "HinfI", "BssHII", "BfrI", "PvuII", "HpaI", "BclI", "AccI", "HindIII"}},
	{Id: "N", Name: "New England Biolabs", Enzymes: []string{"SnaBI", "BspEI", "HpyAV", "AleI", "Fnu4HI", "CviQI", "HaeIII", "Eco53kI", "FseI", "BaeI", "BstBI", "BtsIMutI", "BpmI", "SmaI", "HaeII", "PsiI", "AvaI", "HpyCH4III", "AvrII", "DraI", "Cac8I", "BsaI", "BseYI", "BsaHI", "NruI", "BmgBI", "PspOMI", "SexAI", "BglI", "ClaI", "BsrDI", "PaeR7I", "DpnII", "BssSI", "BstZ17I", "TfiI", "EcoRI", "PspXI", "ApoI", "KasI", "MslI", "DdeI", "Hpy188I", "BcgI", "BsgI", "Sau3AI", "PmlI", "BspHI", "PspGI", "BsiEI", "MspI", "BspCNI", "NsiI", "BpuEI", "MfeI", "NciI", "PshAI", "AclI", "CviAII", "EarI", "BstNI", "DraIII", "SpeI", "TspRI", "MspA1I", "AhdI", "XmnI", "RsaI", "XcmI", "SbfI", "BspDI", "TseI", "MboII", "NcoI", "MseI", "BsmBI", "SmlI", "BseRI", "NlaIII", "AscI", "HincII", "SapI", "FokI", "AfeI", "PpuMI", "BglII", "BslI", "MboI", "PflFI", "SfaNI", "BsiWI", "BtsCI", "BstXI", "SgrAI", "Bsp1286I", "Bsu36I", "HpaII", "SrfI", "MmeI", "PflMI", "CspCI", "MlyI", "ApaLI", "NaeI", "DpnI", "Tth111I", "BsmI", "BstAPI", "PciI", "Esp3I", "StuI", "MluI", "StyD4I", "RsrII", "SacI", "PluTI", "FspI", "MluCI", "HgaI", "AvaII", "BlpI", "NotI", "EcoRV", "XbaI", "BspQI", "EcoNI", "KpnI", "HpyCH4IV", "NheI", "XhoI", "BtgI", "BanI", "BsrFI", "AflIII", "BsaJI", "BfuAI", "BstYI", "AseI", "AbaSI", "BsrI", "MscI", "BsaAI", "SacII", "SalI", "SphI", "AcuI", "BsmFI", "Hpy99I", "SwaI", "ApeKI", "BsaBI", "Acc65I", "HphI", "NarI", "AsiSI", "BamHI", "MspJI", "DrdI", "TspMI", "BfaI", "Tsp45I", "StyI", "BtgZI", "PmeI", "MnlI", "NlaIV", "EcoO109I", "BsiHKAI", "NgoMIV", "PstI", "BbvCI", "BcoDI", "BaeGI", "ScrFI", "PacI", "BsrGI", "BbvI", "BsmAI", "BstUI", "HhaI", "BstEII", "FatI", "BanII", "BccI", "BmrI", "SfiI", "HpyCH4V", "FauI", "Hpy166II", "TaqI", "LpnPI", "NspI", "ZraI", "BceAI", "AlwI", "XmaI", "AatII", "PvuI", "Bpu10I", "HinP1I", "BmtI", "BsaWI", "AflII", "BciVI", "MwoI", "BsoBI", "NdeI", "PaqCI", "EaeI", "BbsI", "AlwNI", "EciI", "BspMI", "ApaI", "EagI", "ScaI", "CviKI-1", "AluI", "BsrBI", "NmeAIII", "FspEI", "HinfI", "SfoI", "BsaXI", "BssHII", "BtsI", "PvuII", "SspI", "PleI", "AciI", "HpaI", "Hpy188III", "SfcI", "BclI", "AccI", "AgeI", "HindIII", "Sau96I"}},
	{Id: "O", Name: "Toyobo Biochemicals", Enzymes: []string{"HaeIII", "SmaI", "BglI", "EcoRI", "DdeI", "SpeI", "NcoI", "HincII", "BglII", "DpnI", "MluI", "SacI", "NotI", "EcoRV", "KpnI", "NheI", "XhoI", "MscI", "SacII", "SalI", "SphI", "BamHI", "PstI", "PacI", "SfiI", "PvuI", "MroI", "ScaI", "AluI", "HinfI", "PvuII", "BclI", "HindIII"}},
	{Id: "Q", Name: "Molecular Biology Resources - CHIMERx", Enzymes: []string{"HaeIII", "SmaI", "AvaI", "TaqII", "DraI", "NruI", "BglI", "ClaI", "EcoRI", "CviJI", "DdeI", "MspI", "NsiI", "AcvI", "TspDTI", "PinAI", "SpeI", "RsaI", "MboII", "NcoI", "HincII", "BglII", "MboI", "BsiHKCI", "BstXI", "HpaII", "DpnI", "Tth111I", "StuI", "MluI", "TspGWI", "RsrII", "SacI", "NotI", "EcoRV", "XbaI", "KpnI", "NheI", "XhoI", "SacII", "SalI", "SphI", "NarI", "BamHI", "BalI", "MnlI", "PstI", "HhaI", "SfiI", "TaqI", "PvuI", "NdeI", "ApaI", "ScaI", "AluI", "HinfI", "BssHII", "PvuII", "SspI", "HpaI", "AccI", "HindIII"}},
	{Id: "R", Name: "Promega Corporation", Enzymes: []string{"HaeIII", "SmaI", "CfoI", "BglI", "ClaI", "EcoRI", "DdeI", "Hsp92I", "MspI", "SpeI", "RsaI", "NcoI", "BstZI", "BglII", "MboI", "HpaII", "Hsp92II", "DpnI", "MluI", "SgfI", "SacI", "NotI", "EcoRV", "XbaI", "KpnI", "NheI", "XhoI", "SacII", "SalI", "SphI", "BamHI", "PstI", "HhaI", "TaqI", "PvuI", "NdeI", "ApaI", "ScaI", "CspI", "AluI", "HinfI", "BclI", "AgeI", "HindIII"}},
	{Id: "S", Name: "Sigma Chemical Corporation", Enzymes: []string{"Asp718I", "HaeIII", "SmaI", "DraI", "CfoI", "NruI", "ClaI", "EcoRI", "DdeI", "NsiI", "KspI", "SpeI", "MunI", "NcoI", "BglII", "DpnI", "BsmI", "MluI", "HindII", "SacI", "Eco47III", "MaeIII", "NotI", "EcoRV", "XbaI", "KpnI", "NheI", "AflIII", "SfuI", "EclXI", "SwaI", "BamHI", "BlnI", "PstI", "PvuI", "NdeI", "AluI", "BfrI", "PvuII", "HpaI", "BclI", "HindIII"}},
	{Id: "V", Name: "Vivantis Technologies", Enzymes: []string{"AsuNHI", "BstSNI", "Rsr2I", "BstHHI", "AspA2I", "SmaI", "AhlI", "VspI", "DraI", "BmiI", "PspEI", "VneI", "BssMI", "PspOMI", "BtuMI", "BglI", "Sfr274I", "EcoRI", "Bst6I", "Ama87I", "PspCI", "EcoICRI", "Sse9I", "MspI", "AclI", "Bse8I", "DraIII", "BstENI", "MspA1I", "RsaI", "SbfI", "BsePI", "Bse1I", "BsnI", "Bse3DI", "MboII", "Bpu14I", "BstFNI", "BstH2I", "FokI", "BstMAI", "BstBAI", "BseX3I", "BglII", "Bsp13I", "Acc16I", "SfaNI", "BstXI", "Zsp2I", "HpaII", "AsiGI", "AfiI", "BmeRI", "Tth111I", "AccBSI", "MluI", "HindII", "Psp124BI", "EcoRV", "BstDSI", "XbaI", "DseDI", "AspLEI", "KpnI", "Bst4CI", "FblI", "BssNI", "BssNAI", "Bbv12I", "PctI", "SalI", "DinI", "HspAI", "SphI", "MhlI", "BstNSI", "AcsI", "Acc65I", "BstX2I", "BamHI", "BshVI", "AsuHPI", "AccB7I", "MnlI", "Bme18I", "PceI", "PstI", "Bse118I", "Tru9I", "BmrFI", "Bso31I", "SfiI", "BstF5I", "Bsp1720I", "TaqI", "ZraI", "BstMBI", "Vha464I", "Bst2UI", "XmaI", "AatII", "Bpu10I", "BmtI", "BstMCI", "AccB1I", "CciNI", "BstDEI", "Msp20I", "Bse21I", "BstAUI", "BstPAI", "Bsp19I", "SmiI", "ApaI", "Ksp22I", "BstV2I", "AluI", "BpuMI", "HinfI", "FriOI", "PvuII", "SspI", "FauNDI", "HpaI", "Sfr303I", "BmcAI", "BssT1I", "AspS9I", "SmiMI", "HindIII", "MroNI", "MroXI"}},
	{Id: "X", Name: "EURx Ltd.", Enzymes: []string{"HaeIII", "BspMAI", "SmaI", "AvaI", "BsuTUI", "TaqII", "DraI", "NruI", "BglI", "ClaI", "SinI", "EcoRI", "CviJI", "DdeI", "BspANI", "Sau3AI", "MspI", "NsiI", "AcvI", "TspDTI", "PinAI", "SpeI", "RsaI", "MboII", "NcoI", "HincII", "FokI", "BspTNI", "BglII", "MboI", "BsiHKCI", "BstXI", "HpaII", "MmeI", "DpnI", "Tth111I", "StuI", "TspGWI", "RsrII", "SacI", "AvaII", "NotI", "EcoRV", "XbaI", "KpnI", "NheI", "XhoI", "SacII", "SalI", "SphI", "NarI", "BamHI", "BalI", "MnlI", "PstI", "HhaI", "BanII", "SfiI", "TaqI", "PvuI", "NdeI", "ApaI", "ScaI", "AluI", "HinfI", "BssHII", "PvuII", "SspI", "HpaI", "AccI", "HindIII"}},
	{Id: "Y", Name: "SinaClon BioScience Co.", Enzymes: []string{"SmaI", "EcoRI", "RsaI", "NcoI", "FokI", "MboI", "BstXI", "KpnI", "BamHI", "SlaI", "BsiSI", "AluI", "HinfI", "HindIII"}},
}
