/*
This file contains a list of Reagenet Suppliers and the restriction enzymes they supply. The data comes from the REBASE database.

THIS FILE IS AUTO-GENERATED. DO NOT MODIFY THIS FILE MANUALLY.

To update the database, run the script in the script directory.
*/
package db

type SupplierRecord struct {
	Id      string
	Name    string
	Enzymes []string
}

var Suppliers = []SupplierRecord{
	{Id: "B", Name: "Thermo Fisher Scientific", Enzymes: []string{"PagI", "BseNI", "MspI", "Bpu1102I", "PauI", "NsbI", "RsaI", "StuI", "Mph1103I", "LguI", "Eco72I", "Eco31I", "MunI", "SchI", "Bsp120I", "DpnI", "MssI", "PspFI", "SaqAI", "LweI", "EcoO109I", "MboI", "BfoI", "XbaI", "AatII", "BglII", "GsuI", "MreI", "BpiI", "NotI", "HapII", "BseSI", "XagI", "Eco24I", "SduI", "BseLI", "Hin6I", "BfuI", "AjiI", "BcnI", "PvuI", "AasI", "BseDI", "Cfr42I", "Eco32I", "Tru1I", "KflI", "MboII", "EcoRII", "Bsu15I", "PdmI", "Psp1406I", "AccI", "AanI", "Cfr13I", "BseXI", "Lsp1109I", "PfoI", "Psp5II", "Bsh1285I", "MvaI", "HincII", "Alw44I", "BmeT110I", "BcuI", "SpeI", "BplI", "Bme1390I", "SsiI", "XceI", "BspOI", "SfiI", "SgeI", "VspI", "EcoT22I", "ClaI", "BveI", "Eco47I", "Hin1I", "HpyF3I", "Bst1107I", "BspPI", "BalI", "SatI", "SfaAI", "SmoI", "HhaI", "SmaI", "BspLI", "TscAI", "HpaI", "NheI", "HphI", "PteI", "Alw26I", "Cfr10I", "PaeI", "HpyF10VI", "PasI", "Van91I", "KspAI", "EcoRV", "SalI", "AjuI", "ScaI", "MnlI", "Bsp143I", "XmiI", "TatI", "SgsI", "AdeI", "MbiI", "BfmI", "BseJI", "NcoI", "BamHI", "Kpn2I", "Eam1105I", "PacI", "PstI", "BclI", "Eco47III", "MlsI", "XapI", "PsyI", "Bpu10I", "XmaJI", "PfeI", "BglI", "SacII", "Bsp119I", "PscI", "BauI", "FokI", "Pfl23II", "SacI", "ApaI", "BmsI", "Alw21I", "HinfI", "NdeI", "SdaI", "SspDI", "CaiI", "BoxI", "Mva1269I", "OliI", "CsiI", "SmiI", "TaqI", "Ppu21I", "AfaI", "FspAI", "Hpy8I", "Eco57I", "BseGI", "PsuI", "PdiI", "NruI", "BsuRI", "AarI", "AloI", "RseI", "EheI", "Eco88I", "Bsh1236I", "BshTI", "CseI", "BseMI", "SgrDI", "EcoRI", "SphI", "SspI", "Eco130I", "HindIII", "MauBI", "RruI", "CpoI", "BseMII", "Ecl136II", "MluI", "Eco147I", "BshNI", "HaeIII", "Bsp1407I", "KpnI", "TasI", "TauI", "BspTI", "TaiI", "AluI", "Cfr9I", "NmuCI", "XhoI", "Csp6I", "TaaI", "Eco52I", "FspBI", "Eco81I", "Hin1II", "HpaII", "BstXI", "Bsp68I", "Acc65I", "DraI", "PvuII", "Eco105I", "Eam1104I", "Esp3I", "Eco91I", "FaqI"}},
	{Id: "C", Name: "Minotech Biotechnology", Enzymes: []string{"SseBI", "RsaI", "MboI", "XbaI", "BglII", "NotI", "BstEII", "PspPI", "ApaLI", "SfiI", "SmaI", "HpaI", "SstI", "NheI", "EcoRV", "BseBI", "BseCI", "SalI", "ScaI", "CspAI", "NcoI", "BamHI", "PstI", "BclI", "BshFI", "BsiSI", "Sau3AI", "BseAI", "BglI", "NaeI", "AsuII", "HinfI", "MspCI", "TaqI", "NruI", "EcoRI", "SphI", "SspI", "HindIII", "StyI", "SnaBI", "BssAI", "SlaI", "KpnI", "AluI", "SgrBI", "PvuII"}},
	{Id: "E", Name: "Agilent Technologies", Enzymes: []string{"DpnI"}},
	{Id: "I", Name: "SibEnzyme Ltd.", Enzymes: []string{"Tru9I", "BstAPI", "MspI", "Bse3DI", "BstKTI", "PspXI", "BstFNI", "BstSFI", "RsaI", "Bsp19I", "BstC8I", "BstACI", "BtrI", "Bse118I", "Bsc4I", "Sfr274I", "BstMBI", "ZraI", "TseFI", "ZrmI", "XbaI", "AatII", "BglII", "Sse9I", "XmaI", "AsuHPI", "BstBAI", "Zsp2I", "PsrI", "AhlI", "PceI", "KroI", "GluI", "AspS9I", "PspLI", "Sfr303I", "Mox20I", "CciI", "BpmI", "Bst2UI", "MboII", "BstNSI", "Fsp4HI", "BstSCI", "PciI", "ArsI", "Bso31I", "PspN4I", "AcsI", "BmuI", "Bst6I", "BstH2I", "ErhI", "SfiI", "VspI", "AclI", "HgaI", "MspR9I", "FatI", "FriOI", "Rsr2I", "DraIII", "Bsp1720I", "BstMAI", "AfeI", "MroNI", "Psp6I", "AgsI", "MhlI", "BstV1I", "DseDI", "GlaI", "MalI", "KroNI", "SmaI", "BspFNI", "PkrI", "AoxI", "FauNDI", "HpaI", "BstSLI", "HindII", "Ple19I", "AjnI", "Mly113I", "Ksp22I", "PciSI", "BlsI", "Bst2BI", "MspA1I", "PalAI", "PspOMI", "RsaNI", "SetI", "SspMI", "EcoRV", "PsiI", "Bbv12I", "BstV2I", "SalI", "MteI", "MnlI", "BisI", "BstPAI", "SfaNI", "BsuI", "Kzo9I", "MroXI", "AccB1I", "AccB7I", "AsuNHI", "BamHI", "Bme18I", "Acc36I", "Bse1I", "MabI", "PstI", "EgeI", "BstF5I", "DriI", "PctI", "Bpu10I", "BstMWI", "FaeI", "BssECI", "AcoI", "BglI", "AccBSI", "HpySE526I", "SmiMI", "Tth111I", "FokI", "PstNI", "EcoICRI", "AsuC2I", "BslFI", "ApaI", "Bsa29I", "HinfI", "PcsI", "Psp124BI", "VneI", "BstAFI", "Bsp13I", "BseX3I", "Acc16I", "SmiI", "TaqI", "AsiSI", "BmtI", "Bpu14I", "PpsI", "RigI", "NruI", "BstAUI", "BsuRI", "HspAI", "Bst4CI", "BstX2I", "AbsI", "AspA2I", "EcoRI", "SphI", "SspI", "AluBI", "Bse8I", "AclWI", "BstSNI", "GsaI", "BarI", "HindIII", "RgaI", "AsiGI", "AcuI", "MluI", "SbfI", "FblI", "BssT1I", "BstDEI", "HaeIII", "KpnI", "PspPPI", "LmnI", "BstENI", "PspCI", "FalI", "AspLEI", "AluI", "Ama87I", "BstHHI", "FaiI", "BspACI", "BsePI", "HpaII", "CciNI", "BstXI", "MfeI", "BstMCI", "BssNAI", "Acc65I", "DraI", "FauI", "PvuII", "Bse21I", "BstDSI", "PspEI"}},
	{Id: "J", Name: "Nippon Gene Co., Ltd.", Enzymes: []string{"MspI", "RsaI", "ScrFI", "EcoT38I", "StuI", "NciI", "BssHII", "EcoO109I", "SwaI", "XbaI", "BglII", "NotI", "NsiI", "BstEII", "NarI", "MboII", "EcoRII", "AccI", "HaeII", "AgeI", "AvaII", "HincII", "Alw44I", "AccIII", "SpeI", "SfiI", "AvaI", "Bsp1286I", "BalI", "HhaI", "NspV", "SmaI", "HpaI", "NheI", "EcoRV", "SalI", "ScaI", "AxyI", "AflII", "NcoI", "BamHI", "NdeII", "PstI", "BclI", "BsmI", "Sau3AI", "BglI", "SacII", "AcyI", "FokI", "SacI", "ApaI", "HinfI", "NdeI", "Sau96I", "AccII", "TaqI", "NruI", "FspI", "EcoRI", "SphI", "SspI", "HindIII", "StyI", "MluI", "HaeIII", "KpnI", "AseI", "AluI", "XhoI", "BstXI", "DraI", "PvuII"}},
	{Id: "K", Name: "Takara Bio Inc.", Enzymes: []string{"MspI", "Bpu1102I", "StuI", "BssHII", "MunI", "DpnI", "EcoO109I", "VpaK11BI", "MboI", "XbaI", "AatII", "BglII", "NotI", "HapII", "BcnI", "PvuI", "BlnI", "MboII", "Psp1406I", "AccI", "Aor51HI", "HaeII", "HincII", "BmeT110I", "AccIII", "SpeI", "ApaLI", "SfiI", "EcoT22I", "ClaI", "XspI", "Hin1I", "Bst1107I", "Bsp1286I", "BalI", "PmaCI", "HhaI", "SmaI", "BciT130I", "HpaI", "NheI", "Sse8387I", "BmgT120I", "Cfr10I", "Van91I", "EcoRV", "PshAI", "SalI", "ScaI", "AflII", "BstPI", "NcoI", "BamHI", "EaeI", "PstI", "Sau3AI", "DdeI", "BglI", "MflI", "NaeI", "SacII", "Tth111I", "FokI", "SacI", "ApaI", "PshBI", "Aor13HI", "HinfI", "NdeI", "AccII", "SmiI", "TaqI", "AfaI", "NruI", "EcoRI", "SphI", "SspI", "HindIII", "CpoI", "SnaBI", "FbaI", "MluI", "BanII", "HaeIII", "Bsp1407I", "BspT107I", "KpnI", "EcoT14I", "AluI", "XhoI", "EcoO65I", "Eco52I", "Eco81I", "BstXI", "BspT104I", "DraI", "PvuII"}},
	{Id: "M", Name: "Roche Applied Science", Enzymes: []string{"Tru9I", "RsaI", "StuI", "MvnI", "BssHII", "MunI", "DpnI", "MaeIII", "MluNI", "SwaI", "XbaI", "AatII", "BglII", "NotI", "NsiI", "PvuI", "Asp700I", "BlnI", "NarI", "AccI", "MvaI", "MaeI", "SpeI", "SfiI", "ClaI", "AflIII", "DraIII", "SfuI", "SmaI", "KspI", "HpaI", "HindII", "NheI", "EcoRV", "SalI", "ScaI", "MroI", "NcoI", "BamHI", "NdeII", "PstI", "BclI", "Eco47III", "BsmI", "Sau3AI", "DdeI", "FokI", "SacI", "ApaI", "Asp718I", "HinfI", "NdeI", "TaqI", "NruI", "MaeII", "EcoRI", "SphI", "HindIII", "SnaBI", "MluI", "HaeIII", "KpnI", "CfoI", "AluI", "SexAI", "XhoI", "BstXI", "BfrI", "DraI", "BbrPI", "PvuII"}},
	{Id: "N", Name: "New England Biolabs", Enzymes: []string{"HpyAV", "BstAPI", "MspI", "BmrI", "Hpy188I", "PspXI", "BstBI", "RsaI", "Bsu36I", "ScrFI", "BspDI", "StuI", "BfaI", "ApoI", "NciI", "CspCI", "BssHII", "BbsI", "DpnI", "SfcI", "NmeAIII", "ZraI", "KasI", "BseYI", "EcoO109I", "SwaI", "MboI", "XbaI", "AatII", "BglII", "CviQI", "NotI", "DpnII", "XmaI", "NsiI", "BspEI", "BmgBI", "BsiHKAI", "AleI", "BsaAI", "EcoNI", "MscI", "NlaIV", "BstEII", "DrdI", "ApeKI", "BbvCI", "PvuI", "Cac8I", "TspMI", "NarI", "BpmI", "MboII", "BaeGI", "AccI", "SfoI", "EciI", "PleI", "PciI", "BsaHI", "HaeII", "AgeI", "AvaII", "HincII", "BsrBI", "BstNI", "BsaJI", "HpyCH4III", "AscI", "CviAII", "SpeI", "BanI", "MseI", "TseI", "ApaLI", "BsiWI", "SfiI", "ClaI", "AflIII", "PaqCI", "AclI", "BsmBI", "SgrAI", "AvaI", "HgaI", "FatI", "DraIII", "LpnPI", "FspEI", "MmeI", "AfeI", "Bsp1286I", "BstUI", "BspCNI", "HhaI", "SmaI", "NgoMIV", "BslI", "HpaI", "NheI", "BcoDI", "BsrDI", "HphI", "PmeI", "MluCI", "MspA1I", "PspOMI", "BfuAI", "StyD4I", "BsrGI", "AvrII", "SapI", "EcoRV", "PshAI", "PsiI", "AlwI", "BssSI", "SalI", "Tsp45I", "BsrI", "ScaI", "MnlI", "SfaNI", "Hpy99I", "BbvI", "AflII", "HpyCH4V", "NspI", "BciVI", "NcoI", "PflMI", "BamHI", "BsoBI", "BsgI", "BsrFI", "EaeI", "PacI", "Hpy166II", "NlaIII", "BtsCI", "PstI", "BclI", "BtsI", "BseRI", "BccI", "Bpu10I", "PspGI", "BsmI", "Sau3AI", "DdeI", "BglI", "NaeI", "SacII", "RsrII", "PmlI", "Tth111I", "BstYI", "FokI", "AciI", "EarI", "BaeI", "BsiEI", "BstZ17I", "SacI", "ApaI", "BsaXI", "HinfI", "XcmI", "NdeI", "PpuMI", "Sau96I", "HpyCH4IV", "BsaI", "SmlI", "TaqI", "BtgZI", "BsmFI", "HinP1I", "AsiSI", "BmtI", "XmnI", "BspMI", "FseI", "NruI", "BceAI", "MslI", "TfiI", "BsmAI", "FspI", "PluTI", "EcoRI", "BspQI", "Hpy188III", "SphI", "SspI", "Fnu4HI", "HindIII", "StyI", "SnaBI", "AcuI", "EagI", "MluI", "SbfI", "BanII", "BcgI", "AlwNI", "PaeR7I", "BsaWI", "HaeIII", "KpnI", "SrfI", "AseI", "MlyI", "BtsIMutI", "AluI", "BspHI", "SexAI", "XhoI", "AbaSI", "CviKI-1", "MspJI", "BtgI", "Eco53kI", "AhdI", "TspRI", "HpaII", "BsaBI", "BstXI", "MfeI", "BlpI", "PflFI", "Acc65I", "DraI", "FauI", "PvuII", "Esp3I", "BpuEI", "MwoI"}},
	{Id: "O", Name: "Toyobo Biochemicals", Enzymes: []string{"DpnI", "BglII", "NotI", "MscI", "PvuI", "HincII", "SpeI", "SfiI", "SmaI", "NheI", "EcoRV", "SalI", "ScaI", "MroI", "NcoI", "BamHI", "PacI", "PstI", "BclI", "DdeI", "BglI", "SacII", "SacI", "HinfI", "EcoRI", "SphI", "HindIII", "MluI", "HaeIII", "KpnI", "AluI", "XhoI", "PvuII"}},
	{Id: "Q", Name: "Molecular Biology Resources - CHIMERx", Enzymes: []string{"MspI", "RsaI", "StuI", "BssHII", "DpnI", "MboI", "XbaI", "BglII", "NotI", "NsiI", "BsiHKCI", "PvuI", "CviJI", "NarI", "MboII", "AccI", "HincII", "SpeI", "SfiI", "ClaI", "AvaI", "BalI", "HhaI", "SmaI", "HpaI", "NheI", "EcoRV", "SalI", "ScaI", "MnlI", "NcoI", "BamHI", "PstI", "DdeI", "TspGWI", "BglI", "SacII", "RsrII", "Tth111I", "SacI", "ApaI", "HinfI", "NdeI", "PinAI", "TaqI", "NruI", "TaqII", "EcoRI", "SphI", "SspI", "HindIII", "MluI", "HaeIII", "AcvI", "KpnI", "TspDTI", "AluI", "XhoI", "HpaII", "BstXI", "DraI", "PvuII"}},
	{Id: "R", Name: "Promega Corporation", Enzymes: []string{"MspI", "RsaI", "DpnI", "MboI", "XbaI", "BglII", "NotI", "PvuI", "CspI", "AgeI", "SpeI", "ClaI", "HhaI", "SmaI", "Hsp92I", "NheI", "EcoRV", "SalI", "ScaI", "NcoI", "BamHI", "PstI", "BclI", "DdeI", "BglI", "SacII", "SacI", "ApaI", "HinfI", "NdeI", "SgfI", "TaqI", "EcoRI", "SphI", "HindIII", "BstZI", "MluI", "HaeIII", "KpnI", "CfoI", "Hsp92II", "AluI", "XhoI", "HpaII"}},
	{Id: "S", Name: "Sigma Chemical Corporation", Enzymes: []string{"MunI", "DpnI", "MaeIII", "SwaI", "XbaI", "BglII", "NotI", "NsiI", "EclXI", "PvuI", "BlnI", "SpeI", "ClaI", "AflIII", "SfuI", "SmaI", "KspI", "HpaI", "HindII", "NheI", "EcoRV", "NcoI", "BamHI", "PstI", "BclI", "Eco47III", "BsmI", "DdeI", "SacI", "Asp718I", "NdeI", "NruI", "EcoRI", "HindIII", "MluI", "HaeIII", "KpnI", "CfoI", "AluI", "BfrI", "DraI", "PvuII"}},
	{Id: "V", Name: "Vivantis Technologies", Enzymes: []string{"Tru9I", "MspI", "Bse3DI", "BstFNI", "RsaI", "Bsp19I", "BtuMI", "Bse118I", "Sfr274I", "BstMBI", "ZraI", "XbaI", "AatII", "BglII", "Sse9I", "XmaI", "AsuHPI", "BstBAI", "Zsp2I", "AhlI", "PceI", "AspS9I", "Vha464I", "Sfr303I", "Bst2UI", "MboII", "BsnI", "BstNSI", "BmeRI", "BpuMI", "Bso31I", "AcsI", "Bst6I", "BstH2I", "SfiI", "VspI", "AclI", "FriOI", "Rsr2I", "DraIII", "Bsp1720I", "BstMAI", "MroNI", "MhlI", "DseDI", "SmaI", "FauNDI", "HpaI", "HindII", "BmcAI", "Ksp22I", "BshVI", "MspA1I", "PspOMI", "EcoRV", "Bbv12I", "BstV2I", "SalI", "BmrFI", "MnlI", "BstPAI", "SfaNI", "MroXI", "AccB1I", "AccB7I", "AsuNHI", "BamHI", "Bme18I", "Bse1I", "PstI", "BstF5I", "PctI", "Bpu10I", "BssNI", "BglI", "AccBSI", "SmiMI", "Tth111I", "FokI", "EcoICRI", "ApaI", "HinfI", "Psp124BI", "VneI", "Bsp13I", "BseX3I", "Acc16I", "SmiI", "TaqI", "BmtI", "Bpu14I", "BstAUI", "AfiI", "HspAI", "Bst4CI", "BstX2I", "AspA2I", "BssMI", "EcoRI", "SphI", "SspI", "Bse8I", "BstSNI", "HindIII", "AsiGI", "MluI", "SbfI", "FblI", "BssT1I", "DinI", "BstDEI", "KpnI", "BstENI", "PspCI", "AspLEI", "AluI", "Ama87I", "BstHHI", "Msp20I", "BsePI", "HpaII", "CciNI", "BstXI", "BstMCI", "BssNAI", "Acc65I", "BmiI", "DraI", "PvuII", "Bse21I", "BstDSI", "PspEI"}},
	{Id: "X", Name: "EURx Ltd.", Enzymes: []string{"MspI", "RsaI", "StuI", "BssHII", "DpnI", "BspTNI", "MboI", "XbaI", "BglII", "NotI", "NsiI", "BsiHKCI", "PvuI", "CviJI", "NarI", "MboII", "AccI", "BsuTUI", "AvaII", "HincII", "SpeI", "SfiI", "ClaI", "AvaI", "MmeI", "BalI", "HhaI", "SinI", "SmaI", "HpaI", "NheI", "EcoRV", "SalI", "ScaI", "MnlI", "BspANI", "BspMAI", "NcoI", "BamHI", "PstI", "Sau3AI", "DdeI", "TspGWI", "BglI", "SacII", "RsrII", "Tth111I", "FokI", "SacI", "ApaI", "HinfI", "NdeI", "PinAI", "TaqI", "NruI", "TaqII", "EcoRI", "SphI", "SspI", "HindIII", "BanII", "HaeIII", "AcvI", "KpnI", "TspDTI", "AluI", "XhoI", "HpaII", "BstXI", "DraI", "PvuII"}},
	{Id: "Y", Name: "SinaClon BioScience Co.", Enzymes: []string{"RsaI", "MboI", "SmaI", "NcoI", "BamHI", "BsiSI", "FokI", "HinfI", "EcoRI", "HindIII", "SlaI", "KpnI", "AluI", "BstXI"}},
}
